### PR TITLE
Toml support

### LINKED ISSUE #47: Support for pyproject.toml
Based on PEP 518 here: https://peps.python.org/pep-0518/#overview-of-file-formats-considered
It seems like `pyproject.toml` is preferred over setup.cfg. We should include some support here for various types. So far:

- setup.cfg (existing)
- pyproject.toml (new)

@ak-gupta thoughts?

### PR DESCRIPTION
**Pull request by fdosani**
Closes #47 

This feature adds in TOML support to co-exist along side `setup.cfg` support:
- created mirrored functions between the 2 to keep the logic separate. 
  - `_convert_toml_array_to_string`, `parse_toml`, and `upgrade_pyproject_toml`
- new dependency is added with `tomlkit`.
- added in some new unit tests

### CODE REVIEW

**Review by ak-gupta — APPROVED** [review]
Nice work!

**Comment by fdosani** [comment]
I think there are some corner cases I still need to capture. Going to push some more commits here.

**Comment by fdosani** [comment]
@ak-gupta I made some additional changes. Exporting wasn't working as intended, and the docs needs some updates too. Ready for review now though.

**Comment by fdosani** [comment]
ping @ak-gupta :)

**Review by ak-gupta — APPROVED** [review]

**Pull request merged**
